### PR TITLE
fix: thread id improvements

### LINKED ISSUE #1309: Incorrect thid in response message
When responding to a DIDComm message with both an `@id` and a `~thread.thid`, it appears that AFJ will use the `@id` as the `thid` of the response message. I believe it should prefer the `thid` that was provided.

### PR DESCRIPTION
**Pull request by TimoGlastra**
Fixes #1309

### CODE REVIEW

File: packages/core/src/modules/credentials/protocol/v1/V1CredentialProtocol.ts [hunk 1]
```diff
@@ -547,7 +547,7 @@ export class V1CredentialProtocol
       // No credential record exists with thread id
       credentialRecord = new CredentialExchangeRecord({
         connectionId: connection?.id,
-        threadId: offerMessage.id,
+        threadId: offerMessage.threadId,
```
Comment (TimoGlastra) [inline packages/core/src/modules/credentials/protocol/v1/V1CredentialProtocol.ts:550]: Found the issue!

**Review by genaris — APPROVED** [review]

**Comment by andrewwhitehead** [comment]
Had to check that AgentMessage.threadId defaults to the id, and it does. Looks good!
