### PR TITLE
fix: remove deprecated multibase and multihash

### LINKED ISSUE #662: ReferenceError: Can't find variable: TextDecoder
Unable to initialize agent.

Using latest @aries-framework/core and @aries-framework/react-native version 0.2.0-alpha.31 (for key derivation method config)

For use in react native

### LINKED ISSUE #673: Property 'TextDecoder' doesn't exist
I am getting this message occasionally using the latest AFJ '[v0.2.0-alpha.34 ](https://github.com/hyperledger/aries-framework-javascript/releases/tag/v0.2.0-alpha.34)

Either when receiving a message from the mediator or from the issuer

DEBUG: Response received {
	"responseMessage": "{\"protected\":\"eyJlbmMiOiJ4Y2hhY2hhMjBwb2x5MTMwNV9pZXRmIiwidHlwIjoiSldNLzEuMCIsImFsZyI6IkF1dGhjcnlwdCIsInJlY2lwaWVudHMiOlt7ImVuY3J5cHRlZF9rZXkiOiJuTFlWTm1JckloVFFmT1pMbUFQR01FbjZuSGF3eTFlSHpBVUd3RmdJZkx2WnBxUUhTZktqYml0QXRBMFdISUlOIiwiaGVhZGVyIjp7ImtpZCI6IjlTUXhOZVYyS0VoVmJkcVJINDlBWHpTd3k0UVpnZW9za2d3UVpoU2c1c2VUIiwiaXYiOiJ4anV2dXBaYzQxZkhWdlZvSW1jdWRwRGNtMG5OVFdDVSIsInNlbmRlciI6Ikd1NXdja3RUR05VRmFZdTB6OUNqSldSTUp2Qm9iUDY4RDloWmREaXVFM3A0UlMyc1lpWGhuV01GTWl0MWIxQVdDam96anAyaWdncU91WThHZXVNYWJYYUE0WHRkSURxT0JoMVJYcW0teURMeWJMRnBUejVGMWxZTk5nQT0ifX1dfQ==\",\"iv\":\"5JR5Y8z1eM1XURuY\",\"ciphertext\":\"8rTwUQ70SOeD-ncw3tH0HjN4HDMIjr-uqpxsLKjrnCODf1EHXENScY96KRy_aJDsiCgSAMncofhAB8km0klDX1F30WmfCTZq6FbmaObRiOMnwhqxo9Laz9j3vxNRTwScEf3lrqBEU8XLcOQwUVQCsF61K_95M5n3gc4rF-vpC9Z3yiFpLE22STTROr7f40nTt_KPY2M-Nj0oZjls7gx33bCHpJh68UwhPjG5o5aIU6Rxib9UcTNhlMWkzHTSvRSIxXUjar-z-B9mDkjuLfJABfDIfsiq9GW5zbUuB2FahBIp4gfRNkuo4k3DbO3QkjRY37YXlwV0aMOQX_lxwmYDABbAUh6-iQ==\",\"tag\":\"jev4B5JaJ2YnbWCCVrRglw==\"}",
	"status": 200
}
	ERROR  ReferenceError: Property 'TextDecoder' doesn't exist, js engine: hermes
	DEBUG  DEBUG: Unable to parse response message
	WARN  Possible Unhandled Promise Rejection (id: 0):
[TimeoutError: Timeout has occurred]

Screenshot 2022-03-13 at 11 39 36 PM

I tested with stable AFJ 0.1.0 and this problem is not there

### PR DESCRIPTION
**Pull request by TimoGlastra**
Removes the dependency on the deprecated `multibase` and `multihash` libraries. They were also using `TextDecoder` which does not work natively in React Native. The replacement library `multiformats` is focused on Node.JS environment so I've also removed it.

I've now added a subset of the functionality that those libraries offer natively to AFJ. This means fewer dependencies which is not a problem I guess. 

Fixes #673 
Fixes #662

### CODE REVIEW

File: packages/core/src/utils/VarintEncoder.ts [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+
+  public static encode(int: number) {
+    const target = new Buffer(VarintEncoder.encodingLength(int))
+    encode(int, target)
+    return target
+  }
+
+  public static encodeTo(int: number, target: Buffer | Uint8Array, offset = 0) {
+    encode(int, target, offset)
+    return target
```
Comment (blu3beri) [inline packages/core/src/utils/VarintEncoder.ts:19]: What does this do?

**Review by blu3beri — APPROVED** [review]
